# Generated by Django 6.0.2 on 2026-02-10 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("memory_size", models.IntegerField(blank=True, null=True)),
                ("memory_unit", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "img_ulr",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=500),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("screen_diagonal", models.FloatField(blank=True, null=True)),
                (
                    "display_resolution",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("characteristics", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
