# Generated by Django 6.0.2 on 2026-02-15 21:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="img_ulr",
        ),
        migrations.AddField(
            model_name="product",
            name="img_url",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=500), blank=True, default=list
            ),
        ),
    ]
