# Generated by Django 6.0.2 on 2026-02-15 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_size', models.IntegerField(blank=True, null=True)),
                ('memory_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_discount', models.IntegerField(blank=True, null=True)),
                ('img_url', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('characteristics', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
